name: Purge SQS Queue Workflow

on:
  workflow_dispatch:
    inputs:
      queue_url:
        description: "SQS Queue URL"
        required: true

jobs:
  purge_queue:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentails
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Purge SQS DLD
        run: |
          aws sqs purge-queue --queue-url ${{ github.event.inputs.queue_url }}
